function Task = g_InverseKinematics_Task(in1)
%G_INVERSEKINEMATICS_TASK
%    TASK = G_INVERSEKINEMATICS_TASK(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    10-Dec-2020 10:11:48

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
q5 = in1(5,:);
q6 = in1(6,:);
q7 = in1(7,:);
q8 = in1(8,:);
q9 = in1(9,:);
q10 = in1(10,:);
q12 = in1(12,:);
q13 = in1(13,:);
q14 = in1(14,:);
t2 = cos(q8);
t3 = cos(q10);
t4 = sin(q8);
t5 = sin(q10);
t6 = cos(q13);
t7 = sin(q13);
Task = [q1;q2;q3;q5;q6;q7;q9;q10;q12;q14;cos(q2).*(-6.830127018916345e-1)-sin(q2).*1.830127018944019e-1+7.0./1.0e2;cos(q5).*(-6.830127018916345e-1)-sin(q5).*1.830127018944019e-1+7.0./1.0e2;t4.*(-4.492499999998706e-1)-t2.*t3.*6.830127018917101e-1-t2.*t5.*1.8301270189412e-1-t3.*t4.*1.584936490555637e-1+t4.*t5.*5.915063509457707e-1+7.0./1.0e2;t4.*5.07499999998706e-2-t2.*t6.*6.830127018917101e-1-t2.*t7.*1.8301270189412e-1-t4.*t6.*1.584936490555637e-1+t4.*t7.*5.915063509457707e-1+7.0./1.0e2];
